project_id = "battlemap"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://keendata-jbk.github.io/battlemap/"]
enable_signup = false

[functions.admin-users]
verify_jwt = true

[functions.map-boundary]
verify_jwt = false

[functions.marketing-qa]
verify_jwt = true
