export const CATEGORY_META = {
  government: { label: "政府资源", short: "政", color: "#1787ff" },
  industry: { label: "产业资源", short: "产", color: "#ff8a1f" },
  platform: { label: "平台资源", short: "平", color: "#1fb889" },
  standalone: { label: "单体项目", short: "单", color: "#7b61e8" },
  partner: { label: "合作伙伴", short: "合", color: "#00a8e8" },
};

export const STAGES = [
  { key: "lead", label: "线索", probability: 5 },
  { key: "discovery", label: "需求挖掘", probability: 20 },
  { key: "solution", label: "方案/标书", probability: 50 },
  { key: "negotiation", label: "商务谈判", probability: 80 },
  { key: "contract", label: "合同签订", probability: 90 },
  { key: "won", label: "赢单", probability: 100 },
];

export const USERS = [
  { id: "u1", name: "张伟", role: "销售", team: "华东一组", status: "启用" },
  { id: "u2", name: "李娜", role: "销售", team: "西南一组", status: "启用" },
  { id: "u3", name: "陈晨", role: "售前", team: "解决方案部", status: "启用" },
  { id: "u4", name: "王磊", role: "销售经理", team: "华东大区", status: "启用" },
  { id: "u5", name: "刘洋", role: "管理员", team: "数字化运营部", status: "启用" },
  { id: "u6", name: "赵敏", role: "销售", team: "华东二组", status: "停用" },
];

export const INITIAL_PROJECTS = [
  {
    id: "P2026001",
    name: "杭州市城市大脑二期项目",
    account: "杭州市数据资源局",
    category: "government",
    region: "华东区域",
    province: "浙江",
    city: "杭州",
    district: "滨江区",
    coordinates: [120.19, 30.19],
    amount: 8600,
    stage: "solution",
    owner: "张伟",
    presales: "陈晨",
    health: "red",
    priority: "P0",
    nextAction: "方案汇报会",
    nextActionDate: "2026-07-03",
    expectedClose: "2026-09-30",
    source: "政府资源转化",
    updatedAt: "2026-06-28 17:20",
    risk: "客户预算审批周期延长",
  },
  {
    id: "P2026002",
    name: "上海徐汇区可信数据空间建设",
    account: "上海徐汇城市数字化有限公司",
    category: "platform",
    region: "华东区域",
    province: "上海",
    city: "上海",
    district: "徐汇区",
    coordinates: [121.44, 31.19],
    amount: 7200,
    stage: "negotiation",
    owner: "张伟",
    presales: "陈晨",
    health: "green",
    priority: "P0",
    nextAction: "确认商务条款",
    nextActionDate: "2026-07-01",
    expectedClose: "2026-08-20",
    source: "平台公司推荐",
    updatedAt: "2026-06-29 09:10",
    risk: "暂无重大风险",
  },
  {
    id: "P2026003",
    name: "苏州工业互联网数据中台",
    account: "苏州高新区产业集团",
    category: "industry",
    region: "华东区域",
    province: "江苏",
    city: "苏州",
    district: "虎丘区",
    coordinates: [120.58, 31.3],
    amount: 5300,
    stage: "discovery",
    owner: "王磊",
    presales: "陈晨",
    health: "yellow",
    priority: "P1",
    nextAction: "补充行业场景清单",
    nextActionDate: "2026-07-02",
    expectedClose: "2026-11-15",
    source: "伙伴联合拓展",
    updatedAt: "2026-06-24 14:35",
    risk: "连续 5 天未更新需求记录",
  },
  {
    id: "P2026004",
    name: "成都金牛区政务数据基座",
    account: "成都市金牛区行政审批局",
    category: "government",
    region: "西南区域",
    province: "四川",
    city: "成都",
    district: "金牛区",
    coordinates: [104.05, 30.69],
    amount: 6200,
    stage: "solution",
    owner: "李娜",
    presales: "陈晨",
    health: "green",
    priority: "P1",
    nextAction: "技术参数确认",
    nextActionDate: "2026-07-04",
    expectedClose: "2026-10-20",
    source: "区域经营",
    updatedAt: "2026-06-28 11:40",
    risk: "暂无重大风险",
  },
  {
    id: "P2026005",
    name: "重庆数字经济产业园湖仓平台",
    account: "重庆数字产业发展有限公司",
    category: "platform",
    region: "西南区域",
    province: "重庆",
    city: "重庆",
    district: "渝北区",
    coordinates: [106.55, 29.65],
    amount: 9800,
    stage: "negotiation",
    owner: "李娜",
    presales: "陈晨",
    health: "yellow",
    priority: "P0",
    nextAction: "高层商务拜访",
    nextActionDate: "2026-07-02",
    expectedClose: "2026-08-31",
    source: "战略客户",
    updatedAt: "2026-06-27 16:05",
    risk: "竞争对手追加资源投入",
  },
  {
    id: "P2026006",
    name: "宁波港航高质量数据集",
    account: "宁波港航产业集团",
    category: "industry",
    region: "华东区域",
    province: "浙江",
    city: "宁波",
    district: "鄞州区",
    coordinates: [121.55, 29.87],
    amount: 4100,
    stage: "discovery",
    owner: "张伟",
    presales: "陈晨",
    health: "green",
    priority: "P1",
    nextAction: "数据样本诊断",
    nextActionDate: "2026-07-08",
    expectedClose: "2026-12-15",
    source: "行业活动",
    updatedAt: "2026-06-29 08:30",
    risk: "暂无重大风险",
  },
  {
    id: "P2026007",
    name: "无锡物联网数据治理平台",
    account: "无锡物联网创新中心",
    category: "standalone",
    region: "华东区域",
    province: "江苏",
    city: "无锡",
    district: "新吴区",
    coordinates: [120.31, 31.49],
    amount: 2800,
    stage: "lead",
    owner: "王磊",
    presales: "陈晨",
    health: "yellow",
    priority: "P2",
    nextAction: "确认预算来源",
    nextActionDate: "2026-07-06",
    expectedClose: "2027-01-20",
    source: "市场线索",
    updatedAt: "2026-06-22 10:15",
    risk: "预算尚未明确",
  },
  {
    id: "P2026008",
    name: "合肥新能源汽车数据中台",
    account: "安徽新能源汽车产业联盟",
    category: "industry",
    region: "华东区域",
    province: "安徽",
    city: "合肥",
    district: "包河区",
    coordinates: [117.23, 31.82],
    amount: 3600,
    stage: "solution",
    owner: "张伟",
    presales: "陈晨",
    health: "green",
    priority: "P1",
    nextAction: "方案评审",
    nextActionDate: "2026-07-09",
    expectedClose: "2026-11-30",
    source: "产业联盟",
    updatedAt: "2026-06-28 18:10",
    risk: "暂无重大风险",
  },
  {
    id: "P2026009",
    name: "福州城市数据运营平台",
    account: "福州大数据发展有限公司",
    category: "platform",
    region: "华东区域",
    province: "福建",
    city: "福州",
    district: "鼓楼区",
    coordinates: [119.3, 26.08],
    amount: 4500,
    stage: "contract",
    owner: "张伟",
    presales: "陈晨",
    health: "green",
    priority: "P1",
    nextAction: "合同法务会签",
    nextActionDate: "2026-07-02",
    expectedClose: "2026-07-25",
    source: "客户续建",
    updatedAt: "2026-06-29 10:20",
    risk: "暂无重大风险",
  },
  {
    id: "P2026010",
    name: "昆明文旅数据资产平台",
    account: "昆明文旅产业集团",
    category: "industry",
    region: "西南区域",
    province: "云南",
    city: "昆明",
    district: "盘龙区",
    coordinates: [102.83, 24.88],
    amount: 3300,
    stage: "discovery",
    owner: "李娜",
    presales: "陈晨",
    health: "red",
    priority: "P1",
    nextAction: "重新约见业务负责人",
    nextActionDate: "2026-06-27",
    expectedClose: "2026-12-20",
    source: "客户转介绍",
    updatedAt: "2026-06-18 09:45",
    risk: "任务逾期且 10 天无跟进",
  },
  {
    id: "P2026011",
    name: "贵阳算力数据服务平台",
    account: "贵阳大数据科创城",
    category: "platform",
    region: "西南区域",
    province: "贵州",
    city: "贵阳",
    district: "观山湖区",
    coordinates: [106.63, 26.65],
    amount: 5700,
    stage: "solution",
    owner: "李娜",
    presales: "陈晨",
    health: "green",
    priority: "P1",
    nextAction: "POC 环境确认",
    nextActionDate: "2026-07-05",
    expectedClose: "2026-10-31",
    source: "生态伙伴",
    updatedAt: "2026-06-28 15:30",
    risk: "暂无重大风险",
  },
  {
    id: "P2026012",
    name: "南京政务知识库建设",
    account: "南京市政务服务中心",
    category: "government",
    region: "华东区域",
    province: "江苏",
    city: "南京",
    district: "建邺区",
    coordinates: [118.78, 32.04],
    amount: 2100,
    stage: "lead",
    owner: "王磊",
    presales: "陈晨",
    health: "green",
    priority: "P2",
    nextAction: "需求访谈",
    nextActionDate: "2026-07-10",
    expectedClose: "2027-02-28",
    source: "政府资源",
    updatedAt: "2026-06-29 11:00",
    risk: "暂无重大风险",
  },
  {
    id: "P2026013",
    name: "厦门供应链数据空间",
    account: "厦门供应链发展集团",
    category: "standalone",
    region: "华东区域",
    province: "福建",
    city: "厦门",
    district: "湖里区",
    coordinates: [118.09, 24.48],
    amount: 3900,
    stage: "negotiation",
    owner: "张伟",
    presales: "陈晨",
    health: "yellow",
    priority: "P1",
    nextAction: "明确数据授权边界",
    nextActionDate: "2026-07-03",
    expectedClose: "2026-09-15",
    source: "平台合作",
    updatedAt: "2026-06-26 12:20",
    risk: "数据授权边界待确认",
  },
  {
    id: "P2026014",
    name: "杭州实施交付伙伴能力认证",
    account: "浙江云启信息技术有限公司",
    category: "partner",
    region: "华东区域",
    province: "浙江",
    city: "杭州",
    district: "余杭区",
    coordinates: [120.03, 30.42],
    amount: 900,
    stage: "contract",
    owner: "张伟",
    presales: "陈晨",
    health: "green",
    priority: "P2",
    nextAction: "完成交付能力复核",
    nextActionDate: "2026-07-07",
    expectedClose: "2026-07-31",
    source: "伙伴招募",
    updatedAt: "2026-06-29 09:40",
    risk: "暂无重大风险",
  },
  {
    id: "P2026015",
    name: "南昌国资数据资产管理平台",
    account: "南昌市国资运营集团",
    category: "government",
    region: "华东区域",
    province: "江西",
    city: "南昌",
    district: "红谷滩区",
    coordinates: [115.86, 28.68],
    amount: 4800,
    stage: "discovery",
    owner: "王磊",
    presales: "陈晨",
    health: "green",
    priority: "P1",
    nextAction: "提交调研提纲",
    nextActionDate: "2026-07-11",
    expectedClose: "2026-12-31",
    source: "区域线索",
    updatedAt: "2026-06-27 09:20",
    risk: "暂无重大风险",
  },
  {
    id: "P2026016",
    name: "绵阳先进制造数据治理项目",
    account: "绵阳科技城产业投资集团",
    category: "industry",
    region: "西南区域",
    province: "四川",
    city: "绵阳",
    district: "涪城区",
    coordinates: [104.68, 31.47],
    amount: 2600,
    stage: "lead",
    owner: "李娜",
    presales: "陈晨",
    health: "yellow",
    priority: "P2",
    nextAction: "补充客户关键人",
    nextActionDate: "2026-07-06",
    expectedClose: "2027-01-31",
    source: "园区资源",
    updatedAt: "2026-06-23 17:10",
    risk: "缺少关键决策人信息",
  },
  {
    id: "P2026017",
    name: "上海国企数据资产入表咨询",
    account: "上海产业发展集团",
    category: "standalone",
    region: "华东区域",
    province: "上海",
    city: "上海",
    district: "浦东新区",
    coordinates: [121.56, 31.23],
    amount: 1600,
    stage: "won",
    owner: "张伟",
    presales: "陈晨",
    health: "green",
    priority: "P2",
    nextAction: "交付启动会",
    nextActionDate: "2026-07-01",
    expectedClose: "2026-06-26",
    source: "老客户增购",
    updatedAt: "2026-06-26 18:00",
    risk: "暂无重大风险",
  },
  {
    id: "P2026018",
    name: "成都数据安全实施伙伴",
    account: "四川数安科技有限公司",
    category: "partner",
    region: "西南区域",
    province: "四川",
    city: "成都",
    district: "高新区",
    coordinates: [104.06, 30.57],
    amount: 1200,
    stage: "solution",
    owner: "李娜",
    presales: "陈晨",
    health: "green",
    priority: "P2",
    nextAction: "联合方案评审",
    nextActionDate: "2026-07-08",
    expectedClose: "2026-09-30",
    source: "伙伴生态",
    updatedAt: "2026-06-28 13:25",
    risk: "暂无重大风险",
  },
];

export const INITIAL_ALERTS = [
  {
    id: "A001",
    projectId: "P2026001",
    level: "red",
    title: "杭州城市大脑二期项目风险升高",
    description: "客户预算审批周期延长，影响金额 8,600 万元",
    time: "10:15",
    status: "待处理",
  },
  {
    id: "A002",
    projectId: "P2026003",
    level: "yellow",
    title: "苏州工业互联网项目久未跟进",
    description: "已超过 5 天未更新需求或沟通记录",
    time: "09:42",
    status: "待处理",
  },
  {
    id: "A003",
    projectId: "P2026010",
    level: "red",
    title: "昆明文旅项目任务已逾期",
    description: "重新约见业务负责人任务逾期 2 天",
    time: "08:50",
    status: "待处理",
  },
  {
    id: "A004",
    projectId: "P2026016",
    level: "info",
    title: "新增标签待匹配到 6 个项目",
    description: "涉及金额合计 12,450 万元",
    time: "09:10",
    status: "已确认",
  },
];

export const SAVED_VIEWS = [
  { id: "v1", name: "华东区重点项目", filter: { region: "华东区域", priority: "P0" }, date: "2026-06-28" },
  { id: "v2", name: "超过 7 天未跟进", filter: { health: "yellow" }, date: "2026-06-26" },
  { id: "v3", name: "产业园区项目全景", filter: { category: "industry" }, date: "2026-06-25" },
  { id: "v4", name: "高价值项目清单", filter: { minAmount: 5000 }, date: "2026-06-24" },
];

export const ROLE_PRESETS = {
  admin: { label: "管理员视角", user: "刘洋", scope: "全部数据" },
  presales: { label: "售前视角", user: "陈晨", scope: "全部数据" },
  sales: { label: "销售视角", user: "张伟", scope: "仅本人数据" },
};
